name: Auto kubernetes apply

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/kubernetes-cd-dev.yaml"
      - "infra/kubernetes/**"

permissions:
  # for google-github-actions/auth setting
  id-token: "write"
  contents: "read"

jobs:
  kubernetes-apply:
    defaults:
      run:
        working-directory: ./kubernetes/
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: my-first-project-12345678
      TARGET-ENVIRONMENT: dev
      CLUSTER-NAME: sample-cluster
      LOCATION: asia-northeast1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-gcp-credentials
        uses: google-github-actions/auth@v0.4.0
        id: gcp-auth
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: cloudnative-sample-account@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        continue-on-error: false

      - name: get gke cred
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: ${{ env.CLUSTER-NAME }}
          location: ${{ env.LOCATION }}
          credentials: ${{ steps.auth.outputs.access_token }}
        continue-on-error: false

      - name: apply
        id: kubectl apply
        run: kubectl apply -f ./
